import 'package:flutter/material.dart';

class AppColors {
  AppColors._();
  static const surface = Color(0xFFFCF9F8);
  static const surfaceDim = Color(0xFFDCD9D9);
  static const surfaceBright = Color(0xFFFCF9F8);
  static const surfaceContainerLowest = Color(0xFFFFFFFF);
  static const surfaceContainerLow = Color(0xFFF6F3F2);
  static const surfaceContainer = Color(0xFFF0EDED);
  static const surfaceContainerHigh = Color(0xFFEAE7E7);
  static const surfaceContainerHighest = Color(0xFFE4E2E1);
  static const onSurface = Color(0xFF1B1C1C);
  static const onSurfaceVariant = Color(0xFF594139);
  static const inverseSurface       = Color(0xFF303030);
  static const inverseOnSurface     = Color(0xFFF3F0F0);
  static const inversePrimary       = Color(0xFFFFB59D);
  static const outline = Color(0xFF8D7168);
  static const outlineVariant = Color(0xFFE1BFB5);
  static const surfaceTint = Color(0xFFAB3500);
  static const primary = Color(0xFFAB3500);
  static const onPrimary = Color(0xFFFFFFFF);
  static const primaryContainer = Color(0xFFFF6B35);
  static const onPrimaryContainer = Color(0xFF5F1900);
  static const primaryFixed = Color(0xFFFFDBD0);
  static const primaryFixedDim = Color(0xFFFFB59D);
  static const onPrimaryFixed = Color(0xFF390C00);
  static const onPrimaryFixedVariant = Color(0xFF832600);
  static const secondary = Color(0xFF006E1C);
  static const onSecondary = Color(0xFFFFFFFF);
  static const secondaryContainer = Color(0xFF91F78E);
  static const onSecondaryContainer = Color(0xFF00731E);
  static const secondaryFixed = Color(0xFF94F990);
  static const secondaryFixedDim = Color(0xFF78DC77);
  static const onSecondaryFixed = Color(0xFF002204);
  static const onSecondaryFixedVariant = Color(0xFF005313);
  static const tertiary             = Color(0xFF5E5F5C);
  static const onTertiary            = Color(0xFFFFFFFF);
  static const tertiaryContainer    = Color(0xFF9A9A96);
  static const onTertiaryContainer  = Color(0xFF313230);
  static const tertiaryFixed = Color(0xFFE3E2DF);
  static const tertiaryFixedDim = Color(0xFFC7C7C3);
  static const onTertiaryFixed = Color(0xFF1B1C1A);
  static const onTertiaryFixedVariant = Color(0xFF464744);
  static const background = Color(0xFFFCF9F8);
  static const onBackground = Color(0xFF1B1C1C);
  static const error = Color(0xFFBA1A1A);
  static const onError = Color(0xFFFFFFFF);
  static const errorContainer = Color(0xFFFFDAD6);
  static const onErrorContainer = Color(0xFF93000A);
  static const mascotTipBg = Color(0xFFFFF7F2);
  static const vibrantButtonShadow = Color(0xFF832600);
}
